### ISSUE TITLE
compare plot gird + solar vs sum of appliances

### ISSUE THREAD

**Issue by j-ti** [j-ti/SES-House#116]

**Comment by flyingdutchman23** [comment]
I just check again whether the data makes sense and according to my analysis it does.

I did this:
```
data = pd.read_csv("./15minute_data_newyork_1222.csv", parse_dates=["local_15min"])
house = data["grid"] + data["solar"]
all(i >= 0 for i in house)
```
that returns `True`. and `all(i >= 0 for i in data["grid"]) return `False`. 

So from this I conclude that our usage of the `grid` column is correct. So I will close this task.
