### ISSUE TITLE
equilibrate capacities and loads (Setup and Data)

### ISSUE THREAD

**Issue by j-ti** [j-ti/SES-House#30]
- Let values make sense together, larger peak capacities/loads
- Take PV data from PecanStreet, it should be fitting to the house loads
- Check if PV data is per unit, it is quiet low for ninja data
- Fit battery capacity to house loads
e. g. like Vermont.ini with a higher peak load

**Comment by flyingdutchman23** [comment]
The values look balanced. The main values, which we can/should still adapt are concerning the battery. But that would go in a different task.
